# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tyler Childs
email: tylerwchilds@gmail.com
description: >
    Personal and Professional Website for Tyler Childs, a Web Designer &amp;
    Developer, currently employed by Netflix and living in the
    San Francisco Bay Area. Passionate about CSS and building stellar user
    experiences, always looking to simplify and streamline anything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tylerchilds.com" # the base hostname & protocol for your site
tagline: Web Designer &amp; Developer

cache_buster: 20200217_1
# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
