# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tyler Childs
email: tylerwchilds@gmail.com
description: >
  This is the final destination for my personal website.
  It's as complex as it will ever need to be and
  there are better things for me to do, to learn and explore.
  There's an entire world out there beyond the boxes
  we tend to put everything into
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tylerchilds.com" # the base hostname & protocol for your site
tagline: Design Technologist & Engineer

# Build settings
markdown: kramdown

sass:
  style: compressed
